// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqtJHn3eN0qEYWatR1AELO5iCJkmw8I4U',
    appId: '1:90821289045:web:13c07fbbce2c535524e0dc',
    messagingSenderId: '90821289045',
    projectId: 'latihan1-69bad',
    authDomain: 'latihan1-69bad.firebaseapp.com',
    databaseURL: 'https://latihan1-69bad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihan1-69bad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVQ_SAQ9yBLTvPwU-3MBWbJm_WSx3Bd98',
    appId: '1:90821289045:android:ae4cf1fdb9c57fb524e0dc',
    messagingSenderId: '90821289045',
    projectId: 'latihan1-69bad',
    databaseURL: 'https://latihan1-69bad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihan1-69bad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7eKAZF856OAFe0cDNYfiPGZtmcRxhVYo',
    appId: '1:90821289045:ios:717f039e1e17d36824e0dc',
    messagingSenderId: '90821289045',
    projectId: 'latihan1-69bad',
    databaseURL: 'https://latihan1-69bad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihan1-69bad.firebasestorage.app',
    iosBundleId: 'com.example.projectUts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7eKAZF856OAFe0cDNYfiPGZtmcRxhVYo',
    appId: '1:90821289045:ios:717f039e1e17d36824e0dc',
    messagingSenderId: '90821289045',
    projectId: 'latihan1-69bad',
    databaseURL: 'https://latihan1-69bad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihan1-69bad.firebasestorage.app',
    iosBundleId: 'com.example.projectUts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqtJHn3eN0qEYWatR1AELO5iCJkmw8I4U',
    appId: '1:90821289045:web:235af77dc2ed1f8124e0dc',
    messagingSenderId: '90821289045',
    projectId: 'latihan1-69bad',
    authDomain: 'latihan1-69bad.firebaseapp.com',
    databaseURL: 'https://latihan1-69bad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihan1-69bad.firebasestorage.app',
  );

}